import type { INodeProperties } from 'n8n-workflow';
import { inputDataField, outputDataField } from '../../shared/descriptions';
import {
	sendCertSignAsMultipart,
	sendValidateSignatureAsMultipart,
	sendWatermarkAsMultipart,
} from '../../shared/binary';
import { binaryRouting, jsonRouting } from '../../shared/routing';

const forSecurity = { resource: ['security'] };
const forOp = (operation: string) => ({ resource: ['security'], operation: [operation] });

// Operations that return JSON instead of a binary file.
const jsonOps = ['getInfo', 'validateSignature'];

export const securityDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: forSecurity },
		options: [
			{
				name: 'Add Password',
				value: 'addPassword',
				action: 'Add a password to a PDF',
				description: 'Encrypt a PDF with a password and permission flags',
				routing: binaryRouting('/api/v1/security/add-password'),
			},
			{
				name: 'Add Watermark',
				value: 'addWatermark',
				action: 'Add a watermark to a PDF',
				description: 'Overlay a text or image watermark on a PDF',
				routing: binaryRouting('/api/v1/security/add-watermark', sendWatermarkAsMultipart),
			},
			{
				name: 'Auto Redact',
				value: 'autoRedact',
				action: 'Automatically redact text in a PDF',
				description: 'Redact the PDF by searching for text',
				routing: binaryRouting('/api/v1/security/auto-redact'),
			},
			{
				name: 'Get PDF Info',
				value: 'getInfo',
				action: 'Get comprehensive info about a PDF',
				description: 'Return comprehensive information about a PDF',
				routing: jsonRouting('/api/v1/security/get-info-on-pdf'),
			},
			{
				name: 'Redact',
				value: 'redact',
				action: 'Redact areas in a PDF',
				description: 'Redact specific areas or pages of a PDF',
				routing: binaryRouting('/api/v1/security/redact'),
			},
			{
				name: 'Remove Certificate Signature',
				value: 'removeCertSign',
				action: 'Remove a digital signature from a PDF',
				description: 'Strip an existing digital signature from a PDF',
				routing: binaryRouting('/api/v1/security/remove-cert-sign'),
			},
			{
				name: 'Remove Password',
				value: 'removePassword',
				action: 'Remove a password from a PDF',
				description: 'Decrypt a password-protected PDF',
				routing: binaryRouting('/api/v1/security/remove-password'),
			},
			{
				name: 'Sanitize',
				value: 'sanitize',
				action: 'Sanitize a PDF',
				description: 'Remove potentially harmful content such as JavaScript and embedded files',
				routing: binaryRouting('/api/v1/security/sanitize-pdf'),
			},
			{
				name: 'Sign With Certificate',
				value: 'certSign',
				action: 'Sign a PDF with a certificate',
				description: 'Apply a digital signature using a certificate',
				routing: binaryRouting('/api/v1/security/cert-sign', sendCertSignAsMultipart),
			},
			{
				name: 'Timestamp',
				value: 'timestamp',
				action: 'Add a trusted timestamp to a PDF',
				description: 'Add an RFC 3161 trusted timestamp to a PDF',
				routing: binaryRouting('/api/v1/security/timestamp-pdf'),
			},
			{
				name: 'Validate Signature',
				value: 'validateSignature',
				action: 'Validate a PDF signature',
				description: 'Validate the digital signatures in a PDF',
				routing: jsonRouting('/api/v1/security/validate-signature', sendValidateSignatureAsMultipart),
			},
		],
		default: 'addPassword',
	},

	{
		...inputDataField,
		displayOptions: { show: forSecurity },
	},
	{
		...outputDataField,
		displayOptions: { show: forSecurity, hide: { operation: jsonOps } },
	},

	// --- Add Password ---
	{
		displayName: 'Key Length',
		name: 'keyLength',
		type: 'options',
		default: 256,
		displayOptions: { show: forOp('addPassword') },
		description: 'Length of the encryption key in bits',
		options: [
			{ name: '40-Bit', value: 40 },
			{ name: '128-Bit', value: 128 },
			{ name: '256-Bit', value: 256 },
		],
		routing: { send: { type: 'body', property: 'keyLength' } },
	},
	{
		displayName: 'User Password',
		name: 'password',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		displayOptions: { show: forOp('addPassword') },
		description: 'Password required to open the document (leave empty for none)',
		routing: { send: { type: 'body', property: 'password' } },
	},
	{
		displayName: 'Owner Password',
		name: 'ownerPassword',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		displayOptions: { show: forOp('addPassword') },
		description: 'Password required to change permissions (leave empty for none)',
		routing: { send: { type: 'body', property: 'ownerPassword' } },
	},
	{
		displayName: 'Permissions',
		name: 'permissions',
		type: 'collection',
		placeholder: 'Add Restriction',
		default: {},
		displayOptions: { show: forOp('addPassword') },
		options: [
			{
				displayName: 'Prevent Assembly',
				name: 'preventAssembly',
				type: 'boolean',
				default: false,
				description: 'Whether to prevent page assembly (insert/delete/rotate). Defaults to false.',
				routing: { send: { type: 'body', property: 'preventAssembly' } },
			},
			{
				displayName: 'Prevent Extract Content',
				name: 'preventExtractContent',
				type: 'boolean',
				default: false,
				description: 'Whether to prevent content extraction. Defaults to false.',
				routing: { send: { type: 'body', property: 'preventExtractContent' } },
			},
			{
				displayName: 'Prevent Extract for Accessibility',
				name: 'preventExtractForAccessibility',
				type: 'boolean',
				default: false,
				description: 'Whether to prevent extraction for accessibility. Defaults to false.',
				routing: { send: { type: 'body', property: 'preventExtractForAccessibility' } },
			},
			{
				displayName: 'Prevent Fill in Form',
				name: 'preventFillInForm',
				type: 'boolean',
				default: false,
				description: 'Whether to prevent form filling. Defaults to false.',
				routing: { send: { type: 'body', property: 'preventFillInForm' } },
			},
			{
				displayName: 'Prevent Modify',
				name: 'preventModify',
				type: 'boolean',
				default: false,
				description: 'Whether to prevent document modification. Defaults to false.',
				routing: { send: { type: 'body', property: 'preventModify' } },
			},
			{
				displayName: 'Prevent Modify Annotations',
				name: 'preventModifyAnnotations',
				type: 'boolean',
				default: false,
				description: 'Whether to prevent modifying annotations. Defaults to false.',
				routing: { send: { type: 'body', property: 'preventModifyAnnotations' } },
			},
			{
				displayName: 'Prevent Printing',
				name: 'preventPrinting',
				type: 'boolean',
				default: false,
				description: 'Whether to prevent printing. Defaults to false.',
				routing: { send: { type: 'body', property: 'preventPrinting' } },
			},
			{
				displayName: 'Prevent Printing Faithful',
				name: 'preventPrintingFaithful',
				type: 'boolean',
				default: false,
				description: 'Whether to prevent high-quality printing. Defaults to false.',
				routing: { send: { type: 'body', property: 'preventPrintingFaithful' } },
			},
		],
	},

	// --- Remove Password ---
	{
		displayName: 'Password',
		name: 'password',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		required: true,
		displayOptions: { show: forOp('removePassword') },
		description: 'The current password of the PDF',
		routing: { send: { type: 'body', property: 'password' } },
	},

	// --- Add Watermark ---
	{
		displayName: 'Watermark Type',
		name: 'watermarkType',
		type: 'options',
		default: 'text',
		displayOptions: { show: forOp('addWatermark') },
		description: 'Whether to watermark with text or an image',
		options: [
			{ name: 'Text', value: 'text' },
			{ name: 'Image', value: 'image' },
		],
		routing: { send: { type: 'body', property: 'watermarkType' } },
	},
	{
		displayName: 'Watermark Text',
		name: 'watermarkText',
		type: 'string',
		default: 'Stirling Software',
		displayOptions: { show: { ...forOp('addWatermark'), watermarkType: ['text'] } },
		description: 'The text to use as the watermark',
		routing: { send: { type: 'body', property: 'watermarkText' } },
	},
	{
		displayName: 'Watermark Image Field Name',
		name: 'watermarkImageFieldName',
		type: 'string',
		default: 'data',
		displayOptions: { show: { ...forOp('addWatermark'), watermarkType: ['image'] } },
		description: 'Name of the input binary field containing the watermark image',
	},
	{
		displayName: 'Font Size',
		name: 'fontSize',
		type: 'number',
		default: 30,
		typeOptions: { minValue: 1 },
		displayOptions: { show: forOp('addWatermark') },
		description: 'Font size of the watermark text (must be at least 1)',
		routing: { send: { type: 'body', property: 'fontSize' } },
	},
	{
		displayName: 'Alphabet',
		name: 'alphabet',
		type: 'options',
		default: 'roman',
		displayOptions: { show: forOp('addWatermark') },
		description: 'Alphabet of the watermark text',
		options: [
			{ name: 'Arabic', value: 'arabic' },
			{ name: 'Chinese', value: 'chinese' },
			{ name: 'Japanese', value: 'japanese' },
			{ name: 'Korean', value: 'korean' },
			{ name: 'Roman', value: 'roman' },
			{ name: 'Thai', value: 'thai' },
		],
		routing: { send: { type: 'body', property: 'alphabet' } },
	},
	{
		displayName: 'Custom Color',
		name: 'customColor',
		type: 'color',
		default: '#000000',
		displayOptions: { show: forOp('addWatermark') },
		description: 'Color of the watermark text',
		routing: { send: { type: 'body', property: 'customColor' } },
	},
	{
		displayName: 'Opacity',
		name: 'opacity',
		type: 'number',
		default: 0.5,
		typeOptions: { minValue: 0, maxValue: 1, numberPrecision: 2 },
		displayOptions: { show: forOp('addWatermark') },
		description: 'Opacity of the watermark, from 0 (transparent) to 1 (opaque)',
		routing: { send: { type: 'body', property: 'opacity' } },
	},
	{
		displayName: 'Width Spacer',
		name: 'widthSpacer',
		type: 'number',
		default: 150,
		displayOptions: { show: forOp('addWatermark') },
		description: 'Horizontal spacing between repeated watermarks',
		routing: { send: { type: 'body', property: 'widthSpacer' } },
	},
	{
		displayName: 'Height Spacer',
		name: 'heightSpacer',
		type: 'number',
		default: 100,
		displayOptions: { show: forOp('addWatermark') },
		description: 'Vertical spacing between repeated watermarks',
		routing: { send: { type: 'body', property: 'heightSpacer' } },
	},
	{
		displayName: 'Convert PDF to Image',
		name: 'convertPDFToImage',
		type: 'boolean',
		default: false,
		displayOptions: { show: forOp('addWatermark') },
		description:
			'Whether to flatten the result to an image so the watermark cannot be removed. Defaults to false.',
		routing: { send: { type: 'body', property: 'convertPDFToImage' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'watermarkAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: forOp('addWatermark') },
		options: [
			{
				displayName: 'Rotation',
				name: 'rotation',
				type: 'number',
				default: 0,
				description: 'Rotation of the watermark in degrees',
				routing: { send: { type: 'body', property: 'rotation' } },
			},
		],
	},

	// --- Sanitize ---
	{
		displayName: 'Remove JavaScript',
		name: 'removeJavaScript',
		type: 'boolean',
		default: true,
		displayOptions: { show: forOp('sanitize') },
		description: 'Whether to remove JavaScript actions. Defaults to true.',
		routing: { send: { type: 'body', property: 'removeJavaScript' } },
	},
	{
		displayName: 'Remove Embedded Files',
		name: 'removeEmbeddedFiles',
		type: 'boolean',
		default: true,
		displayOptions: { show: forOp('sanitize') },
		description: 'Whether to remove embedded files. Defaults to true.',
		routing: { send: { type: 'body', property: 'removeEmbeddedFiles' } },
	},
	{
		displayName: 'Sanitize Options',
		name: 'sanitizeOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: forOp('sanitize') },
		options: [
			{
				displayName: 'Remove Fonts',
				name: 'removeFonts',
				type: 'boolean',
				default: false,
				description: 'Whether to remove embedded fonts. Defaults to false.',
				routing: { send: { type: 'body', property: 'removeFonts' } },
			},
			{
				displayName: 'Remove Links',
				name: 'removeLinks',
				type: 'boolean',
				default: false,
				description: 'Whether to remove links. Defaults to false.',
				routing: { send: { type: 'body', property: 'removeLinks' } },
			},
			{
				displayName: 'Remove Metadata',
				name: 'removeMetadata',
				type: 'boolean',
				default: false,
				description: 'Whether to remove document info metadata. Defaults to false.',
				routing: { send: { type: 'body', property: 'removeMetadata' } },
			},
			{
				displayName: 'Remove XMP Metadata',
				name: 'removeXMPMetadata',
				type: 'boolean',
				default: false,
				description: 'Whether to remove XMP metadata. Defaults to false.',
				routing: { send: { type: 'body', property: 'removeXMPMetadata' } },
			},
		],
	},

	// --- Auto Redact ---
	{
		displayName: 'Text to Redact',
		name: 'listOfText',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		required: true,
		displayOptions: { show: forOp('autoRedact') },
		placeholder: 'e.g. Confidential',
		description: 'Text to search for and redact. Put each term on its own line.',
		routing: { send: { type: 'body', property: 'listOfText' } },
	},
	{
		displayName: 'Use Regex',
		name: 'useRegex',
		type: 'boolean',
		default: false,
		displayOptions: { show: forOp('autoRedact') },
		description: 'Whether to treat the search terms as regular expressions. Defaults to false.',
		routing: { send: { type: 'body', property: 'useRegex' } },
	},
	{
		displayName: 'Whole Word Search',
		name: 'wholeWordSearch',
		type: 'boolean',
		default: false,
		displayOptions: { show: forOp('autoRedact') },
		description: 'Whether to match whole words only. Defaults to false.',
		routing: { send: { type: 'body', property: 'wholeWordSearch' } },
	},
	{
		displayName: 'Redaction Color',
		name: 'redactColor',
		type: 'color',
		default: '#000000',
		displayOptions: { show: forOp('autoRedact') },
		description: 'Color used to cover the redacted text',
		routing: { send: { type: 'body', property: 'redactColor' } },
	},
	{
		displayName: 'Convert PDF to Image',
		name: 'convertPDFToImage',
		type: 'boolean',
		default: false,
		displayOptions: { show: forOp('autoRedact') },
		description:
			'Whether to flatten the result to an image so redacted text cannot be recovered. Defaults to false.',
		routing: { send: { type: 'body', property: 'convertPDFToImage' } },
	},
	{
		displayName: 'Custom Padding',
		name: 'customPadding',
		type: 'number',
		default: 0.1,
		displayOptions: { show: forOp('autoRedact') },
		description: 'Extra padding around each redaction box',
		routing: { send: { type: 'body', property: 'customPadding' } },
	},

	// --- Redact (manual) ---
	{
		displayName: 'Page Numbers',
		name: 'pageNumbers',
		type: 'string',
		default: 'all',
		displayOptions: { show: forOp('redact') },
		description: 'Pages to redact, e.g. "all", "1,3", or "2-5"',
		routing: { send: { type: 'body', property: 'pageNumbers' } },
	},
	{
		displayName: 'Redactions (JSON)',
		name: 'redactions',
		type: 'json',
		default: '[]',
		displayOptions: { show: forOp('redact') },
		description:
			'JSON array of areas to redact, each with page, x, y, width and height. An empty array redacts whole pages listed in Page Numbers.',
		routing: { send: { type: 'body', property: 'redactions' } },
	},
	{
		displayName: 'Page Redaction Color',
		name: 'pageRedactionColor',
		type: 'color',
		default: '#000000',
		displayOptions: { show: forOp('redact') },
		description: 'Color used to fully redact whole pages',
		routing: { send: { type: 'body', property: 'pageRedactionColor' } },
	},
	{
		displayName: 'Convert PDF to Image',
		name: 'convertPDFToImage',
		type: 'boolean',
		default: false,
		displayOptions: { show: forOp('redact') },
		description:
			'Whether to flatten the result to an image so redacted content cannot be recovered. Defaults to false.',
		routing: { send: { type: 'body', property: 'convertPDFToImage' } },
	},

	// --- Timestamp ---
	{
		displayName: 'Timestamp Authority URL',
		name: 'tsaUrl',
		type: 'string',
		default: 'http://timestamp.digicert.com',
		displayOptions: { show: forOp('timestamp') },
		description: 'URL of the RFC 3161 Time Stamp Authority',
		routing: { send: { type: 'body', property: 'tsaUrl' } },
	},

	// --- Validate Signature ---
	{
		displayName: 'Certificate Field Name',
		name: 'certFieldName',
		type: 'string',
		default: '',
		displayOptions: { show: forOp('validateSignature') },
		description:
			'Optional. Name of an input binary field holding a certificate to validate the signature against.',
	},

	// --- Sign With Certificate ---
	{
		displayName: 'Certificate Type',
		name: 'certType',
		type: 'options',
		default: 'PKCS12',
		displayOptions: { show: forOp('certSign') },
		description: 'The type of certificate/keystore to sign with',
		options: [
			{ name: 'JKS', value: 'JKS' },
			{ name: 'PEM', value: 'PEM' },
			{ name: 'PFX', value: 'PFX' },
			{ name: 'PKCS12', value: 'PKCS12' },
		],
		routing: { send: { type: 'body', property: 'certType' } },
	},
	{
		displayName: 'Private Key Field Name',
		name: 'privateKeyFieldName',
		type: 'string',
		default: '',
		displayOptions: { show: { ...forOp('certSign'), certType: ['PEM'] } },
		description: 'Name of the input binary field containing the PEM private key',
	},
	{
		displayName: 'Certificate Field Name',
		name: 'certFieldName',
		type: 'string',
		default: '',
		displayOptions: { show: { ...forOp('certSign'), certType: ['PEM'] } },
		description: 'Name of the input binary field containing the PEM certificate',
	},
	{
		displayName: 'Keystore Field Name',
		name: 'p12FieldName',
		type: 'string',
		default: '',
		displayOptions: { show: { ...forOp('certSign'), certType: ['PKCS12', 'PFX'] } },
		description: 'Name of the input binary field containing the PKCS#12 / PFX keystore',
	},
	{
		displayName: 'Keystore Field Name',
		name: 'jksFieldName',
		type: 'string',
		default: '',
		displayOptions: { show: { ...forOp('certSign'), certType: ['JKS'] } },
		description: 'Name of the input binary field containing the JKS keystore',
	},
	{
		displayName: 'Keystore Password',
		name: 'password',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		displayOptions: { show: forOp('certSign') },
		description: 'Password for the keystore or private key',
		routing: { send: { type: 'body', property: 'password' } },
	},
	{
		displayName: 'Show Signature',
		name: 'showSignature',
		type: 'boolean',
		default: false,
		displayOptions: { show: forOp('certSign') },
		description: 'Whether to draw a visible signature on the page. Defaults to false.',
		routing: { send: { type: 'body', property: 'showSignature' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'certSignAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: forOp('certSign') },
		options: [
			{
				displayName: 'Alias',
				name: 'alias',
				type: 'string',
				default: '',
				description: 'Alias of the certificate to sign with inside the keystore',
				routing: { send: { type: 'body', property: 'alias' } },
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: 'SPDF',
				description: 'Location recorded in the signature',
				routing: { send: { type: 'body', property: 'location' } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: 'SPDF',
				description: 'Name of the signer',
				routing: { send: { type: 'body', property: 'name' } },
			},
			{
				displayName: 'Page Number',
				name: 'pageNumber',
				type: 'number',
				default: 1,
				description: 'Page on which to draw a visible signature',
				routing: { send: { type: 'body', property: 'pageNumber' } },
			},
			{
				displayName: 'Reason',
				name: 'reason',
				type: 'string',
				default: 'Signed by SPDF',
				description: 'Reason recorded in the signature',
				routing: { send: { type: 'body', property: 'reason' } },
			},
			{
				displayName: 'Show Logo',
				name: 'showLogo',
				type: 'boolean',
				default: true,
				description: 'Whether to draw a signature logo. Defaults to true.',
				routing: { send: { type: 'body', property: 'showLogo' } },
			},
		],
	},
];
